apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fintech-workload

resources:
  - ../base
  - ingress/frontend-ingress.yaml

patches:
  - path: patches/frontend-service-clusterip.yaml
